// @lovable.dev/vite-tanstack-config already includes the following — do NOT add them manually
// or the app will break with duplicate plugins:
//   - tanstackStart, viteReact, tailwindcss, tsConfigPaths, nitro (build-only using cloudflare as a default target),
//     componentTagger (dev-only), VITE_* env injection, @ path alias, React/TanStack dedupe,
//     error logger plugins, and sandbox detection (port/host/strictPort).
// You can pass additional config via defineConfig({ vite: { ... }, etc... }) if needed.
import { defineConfig } from "@lovable.dev/vite-tanstack-config";
import fs from "fs";
import path from "path";

function generateFirebaseSW() {
  const apiKey = process.env.VITE_FIREBASE_API_KEY || "";
  const projectId = process.env.VITE_FIREBASE_PROJECT_ID || "";
  const messagingSenderId = process.env.VITE_FIREBASE_MESSAGING_SENDER_ID || "";
  const appId = process.env.VITE_FIREBASE_APP_ID || "";

  let envApiKey = apiKey;
  let envProjectId = projectId;
  let envSenderId = messagingSenderId;
  let envAppId = appId;

  // If environment variables are not in process.env, try reading them from .env files
  if (!envApiKey) {
    try {
      const envPath = path.resolve(process.cwd(), ".env");
      const envLocalPath = path.resolve(process.cwd(), ".env.local");
      let envContent = "";

      if (fs.existsSync(envLocalPath)) {
        envContent = fs.readFileSync(envLocalPath, "utf-8");
      } else if (fs.existsSync(envPath)) {
        envContent = fs.readFileSync(envPath, "utf-8");
      }

      if (envContent) {
        const getVal = (key: string) => {
          const match = envContent.match(new RegExp(`${key}\\s*=\\s*["']?([^"'\\r\\n]+)["']?`));
          return match ? match[1].trim() : "";
        };
        envApiKey = getVal("VITE_FIREBASE_API_KEY");
        envProjectId = getVal("VITE_FIREBASE_PROJECT_ID");
        envSenderId = getVal("VITE_FIREBASE_MESSAGING_SENDER_ID");
        envAppId = getVal("VITE_FIREBASE_APP_ID");
      }
    } catch (e) {
      console.error("Error reading .env file for FCM SW:", e);
    }
  }

  const content = `// Firebase Cloud Messaging Background Service Worker for DigiMitra
// This file is auto-generated by vite.config.ts. Do not edit directly.
importScripts('https://www.gstatic.com/firebasejs/10.9.0/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/10.9.0/firebase-messaging-compat.js');

const firebaseConfig = {
  apiKey: "${envApiKey}",
  authDomain: "${envProjectId}.firebaseapp.com",
  projectId: "${envProjectId}",
  storageBucket: "${envProjectId}.appspot.com",
  messagingSenderId: "${envSenderId}",
  appId: "${envAppId}",
};

if (firebaseConfig.apiKey && firebaseConfig.projectId) {
  firebase.initializeApp(firebaseConfig);

  const messaging = firebase.messaging();

  messaging.onBackgroundMessage((payload) => {
    const title = payload.notification?.title || payload.data?.title || 'DigiMitra Update';
    const options = {
      body: payload.notification?.body || payload.data?.body || 'New village notice or alert available.',
      icon: payload.notification?.icon || payload.data?.icon || '/site-icon.png',
      badge: payload.notification?.badge || payload.data?.badge || '/notification-badge.svg',
      data: {
        url: payload.data?.url || payload.data?.action_url || '/',
        ...payload.data
      },
    };

    self.registration.showNotification(title, options);
  });
}

self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  const targetUrl = event.notification.data?.url || '/';

  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
      for (const client of windowClients) {
        if (client.url.includes(self.location.origin) && 'focus' in client) {
          client.navigate(targetUrl);
          return client.focus();
        }
      }
      if (clients.openWindow) {
        return clients.openWindow(targetUrl);
      }
    })
  );
});
`;

  const publicDir = path.resolve(process.cwd(), "public");
  if (!fs.existsSync(publicDir)) {
    fs.mkdirSync(publicDir, { recursive: true });
  }
  fs.writeFileSync(path.join(publicDir, "firebase-messaging-sw.js"), content, "utf-8");
}

generateFirebaseSW();

import { VitePWA } from "vite-plugin-pwa";

export default defineConfig({
  tanstackStart: {
    // Redirect TanStack Start's bundled server entry to src/server.ts (our SSR error wrapper).
    // nitro/vite builds from this
    server: { entry: "server" },
  },
  vite: {
    build: {
      target: "es2022",
      chunkSizeWarningLimit: 600,
      rollupOptions: {
        output: {
          manualChunks(id) {
            if (id.includes("node_modules")) {
              if (id.includes("lucide-react")) return "vendor-icons";
              if (id.includes("framer-motion")) return "vendor-motion";
              if (id.includes("@tanstack")) return "vendor-tanstack";
              if (id.includes("@supabase")) return "vendor-supabase";
              if (id.includes("recharts") || id.includes("d3-") || id.includes("victory"))
                return "vendor-charts";
              if (id.includes("@google/generative-ai")) return "vendor-genai";
              if (id.includes("firebase") || id.includes("@firebase")) return "vendor-firebase";
              if (
                id.includes("@radix-ui") ||
                id.includes("cmdk") ||
                id.includes("vaul") ||
                id.includes("input-otp")
              )
                return "vendor-ui";
              if (id.includes("date-fns") || id.includes("react-day-picker")) return "vendor-date";
              if (
                id.includes("zod") ||
                id.includes("clsx") ||
                id.includes("tailwind-merge") ||
                id.includes("class-variance-authority")
              )
                return "vendor-utils";
            }
          },
        },
      },
    },
    plugins: [
      VitePWA({
        registerType: "autoUpdate",
        injectRegister: "auto",
        strategies: "generateSW",
        devOptions: {
          enabled: false,
        },
        workbox: {
          globPatterns: ["**/*.{js,css,html,ico,png,svg,jpg,webp,json,woff2}"],
          navigateFallback: "/offline.html",
          navigateFallbackDenylist: [/^\/api/, /^\/_server/],
          cleanupOutdatedCaches: true,
          runtimeCaching: [
            {
              urlPattern: /^https:\/\/fonts\.googleapis\.com\/.*/i,
              handler: "CacheFirst",
              options: {
                cacheName: "google-fonts-cache",
                expiration: {
                  maxEntries: 10,
                  maxAgeSeconds: 60 * 60 * 24 * 365,
                },
                cacheableResponse: {
                  statuses: [0, 200],
                },
              },
            },
            {
              urlPattern: /^https:\/\/fonts\.gstatic\.com\/.*/i,
              handler: "CacheFirst",
              options: {
                cacheName: "gstatic-fonts-cache",
                expiration: {
                  maxEntries: 10,
                  maxAgeSeconds: 60 * 60 * 24 * 365,
                },
                cacheableResponse: {
                  statuses: [0, 200],
                },
              },
            },
            {
              urlPattern: /^https:\/\/[a-z0-9]+\.supabase\.co\/.*/i,
              handler: "NetworkFirst",
              options: {
                cacheName: "supabase-api-cache",
                expiration: {
                  maxEntries: 50,
                  maxAgeSeconds: 60 * 60 * 24, // 1 day
                },
                networkTimeoutSeconds: 5,
                cacheableResponse: {
                  statuses: [0, 200],
                },
              },
            },
          ],
        },
        manifest: {
          name: "GramMitra — Smart Village Ecosystem",
          short_name: "GramMitra",
          description: "Digital Village OS for rural communities",
          theme_color: "#0E2317",
          background_color: "#FFFDF9",
          display: "standalone",
          orientation: "portrait",
          icons: [
            {
              src: "/site-icon.png",
              sizes: "512x512",
              type: "image/png",
              purpose: "any",
            },
            {
              src: "/pwa-192x192.png",
              sizes: "192x192",
              type: "image/png",
              purpose: "any",
            },
            {
              src: "/pwa-512x512.png",
              sizes: "512x512",
              type: "image/png",
              purpose: "any",
            },
            {
              src: "/grammitra_app_icon.png",
              sizes: "512x512",
              type: "image/png",
              purpose: "maskable",
            },
          ],
        },
      }),
    ],
  },
});
