// @lovable.dev/vite-tanstack-config already includes the following — do NOT add them manually
// or the app will break with duplicate plugins:
//   - tanstackStart, viteReact, tailwindcss, tsConfigPaths, nitro (build-only using cloudflare as a default target),
//     componentTagger (dev-only), VITE_* env injection, @ path alias, React/TanStack dedupe,
//     error logger plugins, and sandbox detection (port/host/strictPort).
// You can pass additional config via defineConfig({ vite: { ... }, etc... }) if needed.
import { defineConfig } from "@lovable.dev/vite-tanstack-config";
import fs from "fs";
import path from "path";

function generateFirebaseSW() {
  const apiKey = process.env.VITE_FIREBASE_API_KEY || "";
  const projectId = process.env.VITE_FIREBASE_PROJECT_ID || "";
  const messagingSenderId = process.env.VITE_FIREBASE_MESSAGING_SENDER_ID || "";
  const appId = process.env.VITE_FIREBASE_APP_ID || "";

  let envApiKey = apiKey;
  let envProjectId = projectId;
  let envSenderId = messagingSenderId;
  let envAppId = appId;

  // If environment variables are not in process.env, try reading them from .env files
  if (!envApiKey) {
    try {
      const envPath = path.resolve(process.cwd(), ".env");
      const envLocalPath = path.resolve(process.cwd(), ".env.local");
      let envContent = "";
      
      if (fs.existsSync(envLocalPath)) {
        envContent = fs.readFileSync(envLocalPath, "utf-8");
      } else if (fs.existsSync(envPath)) {
        envContent = fs.readFileSync(envPath, "utf-8");
      }

      if (envContent) {
        const getVal = (key: string) => {
          const match = envContent.match(new RegExp(`${key}\\s*=\\s*["']?([^"'\\r\\n]+)["']?`));
          return match ? match[1].trim() : "";
        };
        envApiKey = getVal("VITE_FIREBASE_API_KEY");
        envProjectId = getVal("VITE_FIREBASE_PROJECT_ID");
        envSenderId = getVal("VITE_FIREBASE_MESSAGING_SENDER_ID");
        envAppId = getVal("VITE_FIREBASE_APP_ID");
      }
    } catch (e) {
      console.error("Error reading .env file for FCM SW:", e);
    }
  }

  const content = `// Firebase Cloud Messaging Background Service Worker for ManaOoru
// This file is auto-generated by vite.config.ts. Do not edit directly.
importScripts('https://www.gstatic.com/firebasejs/10.9.0/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/10.9.0/firebase-messaging-compat.js');

const firebaseConfig = {
  apiKey: "${envApiKey}",
  authDomain: "${envProjectId}.firebaseapp.com",
  projectId: "${envProjectId}",
  storageBucket: "${envProjectId}.appspot.com",
  messagingSenderId: "${envSenderId}",
  appId: "${envAppId}",
};

if (firebaseConfig.apiKey && firebaseConfig.projectId) {
  firebase.initializeApp(firebaseConfig);

  const messaging = firebase.messaging();

  messaging.onBackgroundMessage((payload) => {
    console.log('[firebase-messaging-sw.js] Received background message:', payload);
    const title = payload.notification?.title || payload.data?.title || 'ManaOoru Update';
    const options = {
      body: payload.notification?.body || payload.data?.body || 'New village notice or alert available.',
      icon: payload.notification?.icon || payload.data?.icon || '/site-icon.png',
      badge: payload.notification?.badge || payload.data?.badge || '/notification-badge.svg',
      data: {
        url: payload.data?.url || payload.data?.action_url || '/',
        ...payload.data
      },
    };

    self.registration.showNotification(title, options);
  });
}

self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  const targetUrl = event.notification.data?.url || '/';

  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
      for (const client of windowClients) {
        if (client.url.includes(self.location.origin) && 'focus' in client) {
          client.navigate(targetUrl);
          return client.focus();
        }
      }
      if (clients.openWindow) {
        return clients.openWindow(targetUrl);
      }
    })
  );
});
`;

  const publicDir = path.resolve(process.cwd(), "public");
  if (!fs.existsSync(publicDir)) {
    fs.mkdirSync(publicDir, { recursive: true });
  }
  fs.writeFileSync(path.join(publicDir, "firebase-messaging-sw.js"), content, "utf-8");
  console.log("[Vite FCM Generator] Successfully wrote public/firebase-messaging-sw.js");
}

generateFirebaseSW();

export default defineConfig({
  tanstackStart: {
    // Redirect TanStack Start's bundled server entry to src/server.ts (our SSR error wrapper).
    // nitro/vite builds from this
    server: { entry: "server" },
  },
});
