/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkersRouteImport } from './routes/workers'
import { Route as WorkRouteImport } from './routes/work'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PostWorkerRouteImport } from './routes/post-worker'
import { Route as PostWorkRouteImport } from './routes/post-work'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LandRouteImport } from './routes/land'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as IndexRouteImport } from './routes/index'

const WorkersRoute = WorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PostWorkerRoute = PostWorkerRouteImport.update({
  id: '/post-worker',
  path: '/post-worker',
  getParentRoute: () => rootRouteImport,
} as any)
const PostWorkRoute = PostWorkRouteImport.update({
  id: '/post-work',
  path: '/post-work',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LandRoute = LandRouteImport.update({
  id: '/land',
  path: '/land',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/auth': typeof AuthRoute
  '/land': typeof LandRoute
  '/marketplace': typeof MarketplaceRoute
  '/post-work': typeof PostWorkRoute
  '/post-worker': typeof PostWorkerRoute
  '/services': typeof ServicesRoute
  '/work': typeof WorkRoute
  '/workers': typeof WorkersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/auth': typeof AuthRoute
  '/land': typeof LandRoute
  '/marketplace': typeof MarketplaceRoute
  '/post-work': typeof PostWorkRoute
  '/post-worker': typeof PostWorkerRoute
  '/services': typeof ServicesRoute
  '/work': typeof WorkRoute
  '/workers': typeof WorkersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/auth': typeof AuthRoute
  '/land': typeof LandRoute
  '/marketplace': typeof MarketplaceRoute
  '/post-work': typeof PostWorkRoute
  '/post-worker': typeof PostWorkerRoute
  '/services': typeof ServicesRoute
  '/work': typeof WorkRoute
  '/workers': typeof WorkersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/announcements'
    | '/auth'
    | '/land'
    | '/marketplace'
    | '/post-work'
    | '/post-worker'
    | '/services'
    | '/work'
    | '/workers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/announcements'
    | '/auth'
    | '/land'
    | '/marketplace'
    | '/post-work'
    | '/post-worker'
    | '/services'
    | '/work'
    | '/workers'
  id:
    | '__root__'
    | '/'
    | '/announcements'
    | '/auth'
    | '/land'
    | '/marketplace'
    | '/post-work'
    | '/post-worker'
    | '/services'
    | '/work'
    | '/workers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  AuthRoute: typeof AuthRoute
  LandRoute: typeof LandRoute
  MarketplaceRoute: typeof MarketplaceRoute
  PostWorkRoute: typeof PostWorkRoute
  PostWorkerRoute: typeof PostWorkerRoute
  ServicesRoute: typeof ServicesRoute
  WorkRoute: typeof WorkRoute
  WorkersRoute: typeof WorkersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workers': {
      id: '/workers'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof WorkersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-worker': {
      id: '/post-worker'
      path: '/post-worker'
      fullPath: '/post-worker'
      preLoaderRoute: typeof PostWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-work': {
      id: '/post-work'
      path: '/post-work'
      fullPath: '/post-work'
      preLoaderRoute: typeof PostWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/land': {
      id: '/land'
      path: '/land'
      fullPath: '/land'
      preLoaderRoute: typeof LandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  AuthRoute: AuthRoute,
  LandRoute: LandRoute,
  MarketplaceRoute: MarketplaceRoute,
  PostWorkRoute: PostWorkRoute,
  PostWorkerRoute: PostWorkerRoute,
  ServicesRoute: ServicesRoute,
  WorkRoute: WorkRoute,
  WorkersRoute: WorkersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
