/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkersRouteImport } from './routes/workers'
import { Route as WorkRouteImport } from './routes/work'
import { Route as WeatherRouteImport } from './routes/weather'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as TransportRouteImport } from './routes/transport'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SchemesRouteImport } from './routes/schemes'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProblemsRouteImport } from './routes/problems'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PostWorkerRouteImport } from './routes/post-worker'
import { Route as PostWorkRouteImport } from './routes/post-work'
import { Route as OfficialRouteImport } from './routes/official'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LandRouteImport } from './routes/land'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as DeleteAccountRouteImport } from './routes/delete-account'
import { Route as DealerRegistrationRouteImport } from './routes/dealer-registration'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CompleteProfileRouteImport } from './routes/complete-profile'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperAdminLoginRouteImport } from './routes/super-admin.login'

const WorkersRoute = WorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const WeatherRoute = WeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportRoute = TransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemesRoute = SchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsRoute = ProblemsRouteImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PostWorkerRoute = PostWorkerRouteImport.update({
  id: '/post-worker',
  path: '/post-worker',
  getParentRoute: () => rootRouteImport,
} as any)
const PostWorkRoute = PostWorkRouteImport.update({
  id: '/post-work',
  path: '/post-work',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficialRoute = OfficialRouteImport.update({
  id: '/official',
  path: '/official',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LandRoute = LandRouteImport.update({
  id: '/land',
  path: '/land',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteAccountRoute = DeleteAccountRouteImport.update({
  id: '/delete-account',
  path: '/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const DealerRegistrationRoute = DealerRegistrationRouteImport.update({
  id: '/dealer-registration',
  path: '/dealer-registration',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteProfileRoute = CompleteProfileRouteImport.update({
  id: '/complete-profile',
  path: '/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminLoginRoute = SuperAdminLoginRouteImport.update({
  id: '/super-admin/login',
  path: '/super-admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/announcements': typeof AnnouncementsRoute
  '/auth': typeof AuthRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/dashboard': typeof DashboardRoute
  '/dealer-registration': typeof DealerRegistrationRoute
  '/delete-account': typeof DeleteAccountRoute
  '/emergency': typeof EmergencyRoute
  '/land': typeof LandRoute
  '/marketplace': typeof MarketplaceRoute
  '/official': typeof OfficialRoute
  '/post-work': typeof PostWorkRoute
  '/post-worker': typeof PostWorkerRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/problems': typeof ProblemsRoute
  '/profile': typeof ProfileRoute
  '/schemes': typeof SchemesRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/timeline': typeof TimelineRoute
  '/transport': typeof TransportRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/weather': typeof WeatherRoute
  '/work': typeof WorkRoute
  '/workers': typeof WorkersRoute
  '/super-admin/login': typeof SuperAdminLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/announcements': typeof AnnouncementsRoute
  '/auth': typeof AuthRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/dashboard': typeof DashboardRoute
  '/dealer-registration': typeof DealerRegistrationRoute
  '/delete-account': typeof DeleteAccountRoute
  '/emergency': typeof EmergencyRoute
  '/land': typeof LandRoute
  '/marketplace': typeof MarketplaceRoute
  '/official': typeof OfficialRoute
  '/post-work': typeof PostWorkRoute
  '/post-worker': typeof PostWorkerRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/problems': typeof ProblemsRoute
  '/profile': typeof ProfileRoute
  '/schemes': typeof SchemesRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/timeline': typeof TimelineRoute
  '/transport': typeof TransportRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/weather': typeof WeatherRoute
  '/work': typeof WorkRoute
  '/workers': typeof WorkersRoute
  '/super-admin/login': typeof SuperAdminLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/announcements': typeof AnnouncementsRoute
  '/auth': typeof AuthRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/dashboard': typeof DashboardRoute
  '/dealer-registration': typeof DealerRegistrationRoute
  '/delete-account': typeof DeleteAccountRoute
  '/emergency': typeof EmergencyRoute
  '/land': typeof LandRoute
  '/marketplace': typeof MarketplaceRoute
  '/official': typeof OfficialRoute
  '/post-work': typeof PostWorkRoute
  '/post-worker': typeof PostWorkerRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/problems': typeof ProblemsRoute
  '/profile': typeof ProfileRoute
  '/schemes': typeof SchemesRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/timeline': typeof TimelineRoute
  '/transport': typeof TransportRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/weather': typeof WeatherRoute
  '/work': typeof WorkRoute
  '/workers': typeof WorkersRoute
  '/super-admin/login': typeof SuperAdminLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-assistant'
    | '/announcements'
    | '/auth'
    | '/complete-profile'
    | '/dashboard'
    | '/dealer-registration'
    | '/delete-account'
    | '/emergency'
    | '/land'
    | '/marketplace'
    | '/official'
    | '/post-work'
    | '/post-worker'
    | '/privacy'
    | '/privacy-policy'
    | '/problems'
    | '/profile'
    | '/schemes'
    | '/search'
    | '/services'
    | '/terms'
    | '/timeline'
    | '/transport'
    | '/unauthorized'
    | '/weather'
    | '/work'
    | '/workers'
    | '/super-admin/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-assistant'
    | '/announcements'
    | '/auth'
    | '/complete-profile'
    | '/dashboard'
    | '/dealer-registration'
    | '/delete-account'
    | '/emergency'
    | '/land'
    | '/marketplace'
    | '/official'
    | '/post-work'
    | '/post-worker'
    | '/privacy'
    | '/privacy-policy'
    | '/problems'
    | '/profile'
    | '/schemes'
    | '/search'
    | '/services'
    | '/terms'
    | '/timeline'
    | '/transport'
    | '/unauthorized'
    | '/weather'
    | '/work'
    | '/workers'
    | '/super-admin/login'
  id:
    | '__root__'
    | '/'
    | '/ai-assistant'
    | '/announcements'
    | '/auth'
    | '/complete-profile'
    | '/dashboard'
    | '/dealer-registration'
    | '/delete-account'
    | '/emergency'
    | '/land'
    | '/marketplace'
    | '/official'
    | '/post-work'
    | '/post-worker'
    | '/privacy'
    | '/privacy-policy'
    | '/problems'
    | '/profile'
    | '/schemes'
    | '/search'
    | '/services'
    | '/terms'
    | '/timeline'
    | '/transport'
    | '/unauthorized'
    | '/weather'
    | '/work'
    | '/workers'
    | '/super-admin/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAssistantRoute: typeof AiAssistantRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  AuthRoute: typeof AuthRoute
  CompleteProfileRoute: typeof CompleteProfileRoute
  DashboardRoute: typeof DashboardRoute
  DealerRegistrationRoute: typeof DealerRegistrationRoute
  DeleteAccountRoute: typeof DeleteAccountRoute
  EmergencyRoute: typeof EmergencyRoute
  LandRoute: typeof LandRoute
  MarketplaceRoute: typeof MarketplaceRoute
  OfficialRoute: typeof OfficialRoute
  PostWorkRoute: typeof PostWorkRoute
  PostWorkerRoute: typeof PostWorkerRoute
  PrivacyRoute: typeof PrivacyRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProblemsRoute: typeof ProblemsRoute
  ProfileRoute: typeof ProfileRoute
  SchemesRoute: typeof SchemesRoute
  SearchRoute: typeof SearchRoute
  ServicesRoute: typeof ServicesRoute
  TermsRoute: typeof TermsRoute
  TimelineRoute: typeof TimelineRoute
  TransportRoute: typeof TransportRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  WeatherRoute: typeof WeatherRoute
  WorkRoute: typeof WorkRoute
  WorkersRoute: typeof WorkersRoute
  SuperAdminLoginRoute: typeof SuperAdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workers': {
      id: '/workers'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof WorkersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport': {
      id: '/transport'
      path: '/transport'
      fullPath: '/transport'
      preLoaderRoute: typeof TransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemes': {
      id: '/schemes'
      path: '/schemes'
      fullPath: '/schemes'
      preLoaderRoute: typeof SchemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems': {
      id: '/problems'
      path: '/problems'
      fullPath: '/problems'
      preLoaderRoute: typeof ProblemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-worker': {
      id: '/post-worker'
      path: '/post-worker'
      fullPath: '/post-worker'
      preLoaderRoute: typeof PostWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-work': {
      id: '/post-work'
      path: '/post-work'
      fullPath: '/post-work'
      preLoaderRoute: typeof PostWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/official': {
      id: '/official'
      path: '/official'
      fullPath: '/official'
      preLoaderRoute: typeof OfficialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/land': {
      id: '/land'
      path: '/land'
      fullPath: '/land'
      preLoaderRoute: typeof LandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-account': {
      id: '/delete-account'
      path: '/delete-account'
      fullPath: '/delete-account'
      preLoaderRoute: typeof DeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dealer-registration': {
      id: '/dealer-registration'
      path: '/dealer-registration'
      fullPath: '/dealer-registration'
      preLoaderRoute: typeof DealerRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete-profile': {
      id: '/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof CompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/login': {
      id: '/super-admin/login'
      path: '/super-admin/login'
      fullPath: '/super-admin/login'
      preLoaderRoute: typeof SuperAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAssistantRoute: AiAssistantRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  AuthRoute: AuthRoute,
  CompleteProfileRoute: CompleteProfileRoute,
  DashboardRoute: DashboardRoute,
  DealerRegistrationRoute: DealerRegistrationRoute,
  DeleteAccountRoute: DeleteAccountRoute,
  EmergencyRoute: EmergencyRoute,
  LandRoute: LandRoute,
  MarketplaceRoute: MarketplaceRoute,
  OfficialRoute: OfficialRoute,
  PostWorkRoute: PostWorkRoute,
  PostWorkerRoute: PostWorkerRoute,
  PrivacyRoute: PrivacyRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProblemsRoute: ProblemsRoute,
  ProfileRoute: ProfileRoute,
  SchemesRoute: SchemesRoute,
  SearchRoute: SearchRoute,
  ServicesRoute: ServicesRoute,
  TermsRoute: TermsRoute,
  TimelineRoute: TimelineRoute,
  TransportRoute: TransportRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  WeatherRoute: WeatherRoute,
  WorkRoute: WorkRoute,
  WorkersRoute: WorkersRoute,
  SuperAdminLoginRoute: SuperAdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
